group_imports = "StdExternalCrate"
reorder_imports = true
imports_granularity = "Crate"
array_width = 70
attr_fn_like_width = 80
binop_separator = "Back"
brace_style = "PreferSameLine"
condense_wildcard_suffixes = true
control_brace_style = "AlwaysSameLine"
edition = "2024"
empty_item_single_line = true
fn_call_width = 70
fn_single_line = true
format_code_in_doc_comments = true
format_strings = true
imports_layout = "HorizontalVertical"
reorder_impl_items = true
struct_field_align_threshold = 20
where_single_line = true
